// GENERATED BY java-project-crud.py
package com.camal.businessmanagement;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;


@OpenAPIDefinition(
        info = @Info(
                title = "API",
                version = "v1"
        )
)

public class OpenApiConfig {
}
