// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

import com.camal.businessmanagement.common.ApiError;
import com.camal.businessmanagement.common.ApiEnvelope;
import com.camal.businessmanagement.common.ErrorCode;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.ConstraintViolationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;

@RestControllerAdvice
public class GlobalExceptionHandler {

    private static final Logger log = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    @ExceptionHandler(NotFoundException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> notFound(NotFoundException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(ApiEnvelope.fail(
                ex.getMessage(),
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ex.getErrorCode())
                        .message(ex.getMessage())
                        .details(List.of())
                        .build()
        ));
    }

    @ExceptionHandler(BadRequestException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> badRequest(BadRequestException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiEnvelope.fail(
                ex.getMessage(),
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ex.getErrorCode())
                        .message(ex.getMessage())
                        .details(List.of())
                        .build()
        ));
    }

    @ExceptionHandler(ConflictException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> conflict(ConflictException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body(ApiEnvelope.fail(
                ex.getMessage(),
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ex.getErrorCode())
                        .message(ex.getMessage())
                        .details(List.of())
                        .build()
        ));
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> validation(MethodArgumentNotValidException ex, HttpServletRequest req) {
        List<String> details = ex.getBindingResult().getFieldErrors().stream()
                .map(e -> e.getField() + ": " + e.getDefaultMessage())
                .collect(Collectors.toList());

        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiEnvelope.fail(
                "Validation error",
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ErrorCode.VALIDATION_ERROR)
                        .message("Validation error")
                        .details(details)
                        .build()
        ));
    }

    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> constraint(ConstraintViolationException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiEnvelope.fail(
                "Validation error",
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ErrorCode.VALIDATION_ERROR)
                        .message("Validation error")
                        .details(List.of(ex.getMessage()))
                        .build()
        ));
    }

    @ExceptionHandler(ObjectOptimisticLockingFailureException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> optimistic(ObjectOptimisticLockingFailureException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body(ApiEnvelope.fail(
                "Conflict",
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ErrorCode.CONFLICT)
                        .message("Conflict")
                        .details(List.of("Optimistic lock failure"))
                        .build()
        ));
    }

    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiEnvelope<ApiError>> integrity(DataIntegrityViolationException ex, HttpServletRequest req) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body(ApiEnvelope.fail(
                "Conflict",
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ErrorCode.CONFLICT)
                        .message("Conflict")
                        .details(List.of("Data integrity violation"))
                        .build()
        ));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiEnvelope<ApiError>> general(Exception ex, HttpServletRequest req) {
        log.error("Unhandled exception on {}", req.getRequestURI(), ex);
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ApiEnvelope.fail(
                "Internal error",
                ApiError.builder()
                        .timestamp(Instant.now())
                        .path(req.getRequestURI())
                        .errorCode(ErrorCode.INTERNAL_ERROR)
                        .message("Internal error")
                        .details(List.of())
                        .build()
        ));
    }
}
