// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

import com.camal.businessmanagement.common.ErrorCode;
import lombok.Getter;

@Getter
public class NotFoundException extends RuntimeException {
    private final ErrorCode errorCode = ErrorCode.NOT_FOUND;

    public NotFoundException(String message) {
        super(message);
    }
}
