// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

public class ProductNotFound extends NotFoundException {
    public ProductNotFound(Object idOrHint) {
        super("Product not found: " + idOrHint);
    }
}
