// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

public class TestNotFound extends NotFoundException {
    public TestNotFound(Object idOrHint) {
        super("Test not found: " + idOrHint);
    }
}
