// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.dto.product;

import jakarta.validation.constraints.NotNull;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductUpdateRequestDto {
    @NotNull
    private Long version;
    private String url;
    private String productName;
    private Double boughtPrice;
    private Double sellPrice;
    private String description;
}
