// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

import com.camal.businessmanagement.common.ErrorCode;
import lombok.Getter;

@Getter
public class BadRequestException extends RuntimeException {
    private final ErrorCode errorCode = ErrorCode.BAD_REQUEST;

    public BadRequestException(String message) {
        super(message);
    }
}
