// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

import com.camal.businessmanagement.common.ErrorCode;
import lombok.Getter;

@Getter
public class ConflictException extends RuntimeException {
    private final ErrorCode errorCode = ErrorCode.CONFLICT;

    public ConflictException(String message) {
        super(message);
    }
}
