// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.exception;

public class GuardNotFound extends NotFoundException {
    public GuardNotFound(Object idOrHint) {
        super("Guard not found: " + idOrHint);
    }
}
