// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.mapper;

import com.camal.businessmanagement.dto.product.guard.GuardCreateRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardPatchRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardResponseDto;
import com.camal.businessmanagement.dto.product.guard.GuardUpdateRequestDto;
import com.camal.businessmanagement.entity.Guard;
import java.util.*;
import java.util.stream.Collectors;
import org.mapstruct.*;

@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        builder = @org.mapstruct.Builder(disableBuilder = true)
)
public interface GuardMapper {

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    Guard toEntity(GuardCreateRequestDto dto);

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromUpdateDto(@MappingTarget Guard entity, GuardUpdateRequestDto dto);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromPatchDto(@MappingTarget Guard entity, GuardPatchRequestDto dto);


    GuardResponseDto toDto(Guard entity);


}
