// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.service;

import com.camal.businessmanagement.dto.product.test.TestCreateRequestDto;
import com.camal.businessmanagement.dto.product.test.TestPatchRequestDto;
import com.camal.businessmanagement.dto.product.test.TestResponseDto;
import com.camal.businessmanagement.dto.product.test.TestUpdateRequestDto;
import com.camal.businessmanagement.entity.Test;
import com.camal.businessmanagement.exception.BadRequestException;
import com.camal.businessmanagement.exception.ConflictException;
import com.camal.businessmanagement.exception.TestNotFound;
import com.camal.businessmanagement.mapper.TestMapper;
import com.camal.businessmanagement.repository.TestRepository;
import com.camal.businessmanagement.spec.TestSpecifications;
import java.util.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Transactional
public class TestService {

    private final TestRepository repository;
private final TestMapper mapper;

    public TestResponseDto create(TestCreateRequestDto dto) {
        Test entity = mapper.toEntity(dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    public TestResponseDto update(Long id, TestUpdateRequestDto dto) {
        Test entity = repository.findById(id)
                .orElseThrow(() -> new TestNotFound(id));

        if (dto.getVersion() == null) {
            throw new BadRequestException("version is required");
        }
        if (entity.getVersion() != null && !Objects.equals(entity.getVersion(), dto.getVersion())) {
            throw new ConflictException("version mismatch");
        }

        mapper.updateFromUpdateDto(entity, dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    public TestResponseDto patch(Long id, TestPatchRequestDto dto) {
        Test entity = repository.findById(id)
                .orElseThrow(() -> new TestNotFound(id));

        if (dto.getVersion() == null) {
            throw new BadRequestException("version is required");
        }
        if (entity.getVersion() != null && !Objects.equals(entity.getVersion(), dto.getVersion())) {
            throw new ConflictException("version mismatch");
        }

        mapper.updateFromPatchDto(entity, dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    @Transactional(readOnly = true)
    public TestResponseDto get(Long id) {
        Test entity = repository.findById(id)
                .orElseThrow(() -> new TestNotFound(id));
        return mapper.toDto(entity);
    }

    @Transactional(readOnly = true)
    public Page<TestResponseDto> list(Map<String, String> params, Pageable pageable) {
        var spec = TestSpecifications.fromParams(params);
        return repository.findAll(spec, pageable).map(mapper::toDto);
    }

    @Transactional(readOnly = true)
    public Page<TestResponseDto> search(Map<String, String> params, Pageable pageable) {
        return list(params, pageable);
    }

    public void delete(Long id) {
        Test entity = repository.findById(id)
                .orElseThrow(() -> new TestNotFound(id));
        entity.setDeleted(true);
        repository.save(entity);
    }
}
