// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.common;

import lombok.Builder;
import lombok.Data;

import java.time.Instant;
import java.util.List;

@Data
@Builder
public class ApiError {
    private Instant timestamp;
    private String path;
    private ErrorCode errorCode;
    private String message;
    private List<String> details;
}
