// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.common;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class ApiEnvelope<T> {
    private boolean success;
    private String message;
    private T data;

    public static <T> ApiEnvelope<T> ok(String message, T data) {
        return new ApiEnvelope<>(true, message, data);
    }
    public static <T> ApiEnvelope<T> fail(String message, T data) {
        return new ApiEnvelope<>(false, message, data);
    }
}
