// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.repository;

import com.camal.businessmanagement.entity.Guard;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface GuardRepository extends JpaRepository<Guard, Long>, JpaSpecificationExecutor<Guard> {
}
