// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.repository;

import com.camal.businessmanagement.entity.Test;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface TestRepository extends JpaRepository<Test, Long>, JpaSpecificationExecutor<Test> {
}
