// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.controller;

import com.camal.businessmanagement.common.ApiEnvelope;
import com.camal.businessmanagement.common.PageResponse;
import com.camal.businessmanagement.dto.product.test.TestCreateRequestDto;
import com.camal.businessmanagement.dto.product.test.TestPatchRequestDto;
import com.camal.businessmanagement.dto.product.test.TestResponseDto;
import com.camal.businessmanagement.dto.product.test.TestUpdateRequestDto;
import com.camal.businessmanagement.service.TestService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@Tag(name = "Test", description = "Test CRUD API")
@RestController
@Validated
@RequestMapping("/api/v1/tests")
@RequiredArgsConstructor
public class TestController {

    private final TestService service;

    @Operation(summary = "Create Test")
    @PostMapping
    public ResponseEntity<ApiEnvelope<TestResponseDto>> create(@Valid @RequestBody TestCreateRequestDto dto) {
        TestResponseDto created = service.create(dto);
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(created.getId())
                .toUri();
        return ResponseEntity.created(location).body(ApiEnvelope.ok("created", created));
    }

    @Operation(summary = "Replace Test (PUT)", description = "Full replace")
    @PutMapping("/{id}")
    public ResponseEntity<ApiEnvelope<TestResponseDto>> update(@PathVariable Long id,
            @Valid @RequestBody TestUpdateRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.update(id, dto)));
    }

    @Operation(summary = "Partial update Test (PATCH)", description = "Partial update (null ignored)")
    @PatchMapping("/{id}")
    public ResponseEntity<ApiEnvelope<TestResponseDto>> patch(@PathVariable Long id,
            @Valid @RequestBody TestPatchRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.patch(id, dto)));
    }

    @Operation(summary = "Get Test by id")
    @GetMapping("/{id}")
    public ResponseEntity<ApiEnvelope<TestResponseDto>> get(@PathVariable Long id) {
        return ResponseEntity.ok(ApiEnvelope.ok("ok", service.get(id)));
    }

    @Operation(summary = "List Test", description = "Filters via query params: q, field, minField/maxField, fromField/toField, relationId, relationIds")
    @GetMapping
    public ResponseEntity<ApiEnvelope<PageResponse<TestResponseDto>>> list(@RequestParam Map<String, String> params,
            Pageable pageable) {
        params.remove("page");
        params.remove("size");
        params.remove("sort");
        Page<TestResponseDto> page = service.list(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Search Test", description = "Alias for list with same filters")
    @GetMapping("/search")
    public ResponseEntity<ApiEnvelope<PageResponse<TestResponseDto>>> search(@RequestParam Map<String, String> params,
            Pageable pageable) {
        params.remove("page");
        params.remove("size");
        params.remove("sort");
        Page<TestResponseDto> page = service.search(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Delete Test (soft delete)")
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.delete(id);
        return ResponseEntity.noContent().build();
    }
}
