// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.mapper;

import com.camal.businessmanagement.dto.product.product.ProductCreateRequestDto;
import com.camal.businessmanagement.dto.product.product.ProductPatchRequestDto;
import com.camal.businessmanagement.dto.product.product.ProductResponseDto;
import com.camal.businessmanagement.dto.product.product.ProductUpdateRequestDto;
import com.camal.businessmanagement.entity.Product;
import java.util.*;
import java.util.stream.Collectors;
import org.mapstruct.*;

@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        builder = @org.mapstruct.Builder(disableBuilder = true)
)
public interface ProductMapper {

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    Product toEntity(ProductCreateRequestDto dto);

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromUpdateDto(@MappingTarget Product entity, ProductUpdateRequestDto dto);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromPatchDto(@MappingTarget Product entity, ProductPatchRequestDto dto);


    ProductResponseDto toDto(Product entity);


}
