// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.mapper;

import com.camal.businessmanagement.dto.product.test.TestCreateRequestDto;
import com.camal.businessmanagement.dto.product.test.TestPatchRequestDto;
import com.camal.businessmanagement.dto.product.test.TestResponseDto;
import com.camal.businessmanagement.dto.product.test.TestUpdateRequestDto;
import com.camal.businessmanagement.entity.Test;
import java.util.*;
import java.util.stream.Collectors;
import org.mapstruct.*;

@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        builder = @org.mapstruct.Builder(disableBuilder = true)
)
public interface TestMapper {

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    Test toEntity(TestCreateRequestDto dto);

    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromUpdateDto(@MappingTarget Test entity, TestUpdateRequestDto dto);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateFromPatchDto(@MappingTarget Test entity, TestPatchRequestDto dto);


    TestResponseDto toDto(Test entity);


}
