// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.controller;

import com.camal.businessmanagement.common.ApiEnvelope;
import com.camal.businessmanagement.common.PageResponse;
import com.camal.businessmanagement.dto.product.guard.GuardCreateRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardPatchRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardResponseDto;
import com.camal.businessmanagement.dto.product.guard.GuardUpdateRequestDto;
import com.camal.businessmanagement.service.GuardService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Tag(name = "Guard", description = "Guard CRUD API")
@RestController
@Validated
@RequestMapping("/api/v1/guards")
@RequiredArgsConstructor
public class GuardController {

    private final GuardService service;

    @Operation(summary = "Create Guard")
    @PostMapping
    public ResponseEntity<ApiEnvelope<GuardResponseDto>> create(@Valid @RequestBody GuardCreateRequestDto dto) {
        GuardResponseDto created = service.create(dto);
        URI location = URI.create("/api/v1/guards" + "/" + created.getId());
        return ResponseEntity.created(location).body(ApiEnvelope.ok("created", created));
    }

    @Operation(summary = "Replace Guard (PUT)", description = "Full replace")
    @PutMapping("/{id}")
    public ResponseEntity<ApiEnvelope<GuardResponseDto>> update(@PathVariable Long id, @Valid @RequestBody GuardUpdateRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.update(id, dto)));
    }

    @Operation(summary = "Partial update Guard (PATCH)", description = "Partial update (null ignored)")
    @PatchMapping("/{id}")
    public ResponseEntity<ApiEnvelope<GuardResponseDto>> patch(@PathVariable Long id, @Valid @RequestBody GuardPatchRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.patch(id, dto)));
    }

    @Operation(summary = "Get Guard by id")
    @GetMapping("/{id}")
    public ResponseEntity<ApiEnvelope<GuardResponseDto>> get(@PathVariable Long id) {
        return ResponseEntity.ok(ApiEnvelope.ok("ok", service.get(id)));
    }

    @Operation(summary = "List Guard", description = "Filters via query params: q, field, minField/maxField, fromField/toField, relationId, relationIds")
    @GetMapping
    public ResponseEntity<ApiEnvelope<PageResponse<GuardResponseDto>>> list(@RequestParam Map<String, String> params, Pageable pageable) {
        Page<GuardResponseDto> page = service.list(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Search Guard", description = "Alias for list with same filters")
    @GetMapping("/search")
    public ResponseEntity<ApiEnvelope<PageResponse<GuardResponseDto>>> search(@RequestParam Map<String, String> params, Pageable pageable) {
        Page<GuardResponseDto> page = service.search(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Delete Guard (soft delete)")
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.delete(id);
        return ResponseEntity.noContent().build();
    }
}
