// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.controller;

import com.camal.businessmanagement.common.ApiEnvelope;
import com.camal.businessmanagement.common.PageResponse;
import com.camal.businessmanagement.dto.product.product.ProductCreateRequestDto;
import com.camal.businessmanagement.dto.product.product.ProductPatchRequestDto;
import com.camal.businessmanagement.dto.product.product.ProductResponseDto;
import com.camal.businessmanagement.dto.product.product.ProductUpdateRequestDto;
import com.camal.businessmanagement.service.ProductService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Tag(name = "Product", description = "Product CRUD API")
@RestController
@Validated
@RequestMapping("/api/v1/products")
@RequiredArgsConstructor
public class ProductController {

    private final ProductService service;

    @Operation(summary = "Create Product")
    @PostMapping
    public ResponseEntity<ApiEnvelope<ProductResponseDto>> create(@Valid @RequestBody ProductCreateRequestDto dto) {
        ProductResponseDto created = service.create(dto);
        URI location = URI.create("/api/v1/products" + "/" + created.getId());
        return ResponseEntity.created(location).body(ApiEnvelope.ok("created", created));
    }

    @Operation(summary = "Replace Product (PUT)", description = "Full replace")
    @PutMapping("/{id}")
    public ResponseEntity<ApiEnvelope<ProductResponseDto>> update(@PathVariable Long id, @Valid @RequestBody ProductUpdateRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.update(id, dto)));
    }

    @Operation(summary = "Partial update Product (PATCH)", description = "Partial update (null ignored)")
    @PatchMapping("/{id}")
    public ResponseEntity<ApiEnvelope<ProductResponseDto>> patch(@PathVariable Long id, @Valid @RequestBody ProductPatchRequestDto dto) {
        return ResponseEntity.ok(ApiEnvelope.ok("updated", service.patch(id, dto)));
    }

    @Operation(summary = "Get Product by id")
    @GetMapping("/{id}")
    public ResponseEntity<ApiEnvelope<ProductResponseDto>> get(@PathVariable Long id) {
        return ResponseEntity.ok(ApiEnvelope.ok("ok", service.get(id)));
    }

    @Operation(summary = "List Product", description = "Filters via query params: q, field, minField/maxField, fromField/toField, relationId, relationIds")
    @GetMapping
    public ResponseEntity<ApiEnvelope<PageResponse<ProductResponseDto>>> list(@RequestParam Map<String, String> params, Pageable pageable) {
        Page<ProductResponseDto> page = service.list(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Search Product", description = "Alias for list with same filters")
    @GetMapping("/search")
    public ResponseEntity<ApiEnvelope<PageResponse<ProductResponseDto>>> search(@RequestParam Map<String, String> params, Pageable pageable) {
        Page<ProductResponseDto> page = service.search(params, pageable);
        return ResponseEntity.ok(ApiEnvelope.ok("ok", PageResponse.from(page)));
    }

    @Operation(summary = "Delete Product (soft delete)")
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        service.delete(id);
        return ResponseEntity.noContent().build();
    }
}
