// GENERATED BY java-project-crud.py
package com.camal.businessmanagement.service;

import com.camal.businessmanagement.dto.product.guard.GuardCreateRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardPatchRequestDto;
import com.camal.businessmanagement.dto.product.guard.GuardResponseDto;
import com.camal.businessmanagement.dto.product.guard.GuardUpdateRequestDto;
import com.camal.businessmanagement.entity.Guard;
import com.camal.businessmanagement.exception.BadRequestException;
import com.camal.businessmanagement.exception.ConflictException;
import com.camal.businessmanagement.exception.GuardNotFound;
import com.camal.businessmanagement.mapper.GuardMapper;
import com.camal.businessmanagement.repository.GuardRepository;
import com.camal.businessmanagement.spec.GuardSpecifications;
import java.util.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Transactional
public class GuardService {

    private final GuardRepository repository;
private final GuardMapper mapper;

    public GuardResponseDto create(GuardCreateRequestDto dto) {
        Guard entity = mapper.toEntity(dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    public GuardResponseDto update(Long id, GuardUpdateRequestDto dto) {
        Guard entity = repository.findById(id)
                .orElseThrow(() -> new GuardNotFound(id));

        if (dto.getVersion() == null) {
            throw new BadRequestException("version is required");
        }
        if (entity.getVersion() != null && !Objects.equals(entity.getVersion(), dto.getVersion())) {
            throw new ConflictException("version mismatch");
        }

        mapper.updateFromUpdateDto(entity, dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    public GuardResponseDto patch(Long id, GuardPatchRequestDto dto) {
        Guard entity = repository.findById(id)
                .orElseThrow(() -> new GuardNotFound(id));

        if (dto.getVersion() == null) {
            throw new BadRequestException("version is required");
        }
        if (entity.getVersion() != null && !Objects.equals(entity.getVersion(), dto.getVersion())) {
            throw new ConflictException("version mismatch");
        }

        mapper.updateFromPatchDto(entity, dto);

        entity = repository.save(entity);
        return mapper.toDto(entity);
    }

    @Transactional(readOnly = true)
    public GuardResponseDto get(Long id) {
        Guard entity = repository.findById(id)
                .orElseThrow(() -> new GuardNotFound(id));
        return mapper.toDto(entity);
    }

    @Transactional(readOnly = true)
    public Page<GuardResponseDto> list(Map<String, String> params, Pageable pageable) {
        var spec = GuardSpecifications.fromParams(params);
        return repository.findAll(spec, pageable).map(mapper::toDto);
    }

    @Transactional(readOnly = true)
    public Page<GuardResponseDto> search(Map<String, String> params, Pageable pageable) {
        return list(params, pageable);
    }

    public void delete(Long id) {
        Guard entity = repository.findById(id)
                .orElseThrow(() -> new GuardNotFound(id));
        entity.setDeleted(true);
        repository.save(entity);
    }
}
